name: ARTenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - importlib_resources
  - matplotlib>=3.6   
  - mayavi>=4.7.2
  - numpy>=1.21.5
  - python=3.9
  - quaternion>=2022.4.2
  - pyvista>=0.39