name: testARTenv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ca-certificates
  - importlib_resources
  - matplotlib=3.5.3
  - mayavi>=4.7.2
  - numpy>=1.21.5
  - python=3.9
  - quaternion>=2022.4.2
  - scipy>=1.7.3
  - vtk>=9.0.3
